### ISSUE TITLE
RabinKarpSearch

### ISSUE THREAD

**Issue by danrog303** [danrog303/search-algorithms#17]
**Co działa?**
1. wyszukiwanie polskich znaków
2. wyszukiwanie w dużym zbiorze znaków (testowano dla 1000000)

**Co trzeba poprawić?**
1. Nazwy zmiennych nic nie mówią. Nie wiadomo, czym jest na przykład d lub q.  
*Nie trzeba się bać długich nazw zmiennych: nazwa zmiennej "hashPatternValue" to o wiele lepsza nazwa, niż "p".*

*Proszę o przypięcie reakcji 👀 pod wpisem aby potwierdzić przeczytanie. Issue zostanie zamknięte po zaakceptowaniu pull requesta zawierającego powyższe zmiany.*

**Comment by DawidLanecki** [comment]
pull request dodany
